// SPDX-License-Identifier: MIT
// AUTO-GENERATED by GLYPH Rust Prover - DO NOT EDIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "./GLYPHVerifier.sol";

/**
 * @title GeneratedRealProofTest
 * @notice End-to-End tests with real packed calldata from the Rust prover.
 *
 * CRITICAL: These tests prove GLYPHVerifier actually verifies!
 * - Valid proofs: should return true
 * - Tampered proofs: should return false
 */
contract GeneratedRealProofTest is Test {
    address internal constant TARGET = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;

    function setUp() public {
        vm.chainId(31337);
        GLYPHVerifier impl = new GLYPHVerifier();
        vm.etch(TARGET, address(impl).code);
    }

    function test_GLYPH_RealProof_HASH_Succeeds() public {
        bytes memory proof = hex"bc3ede294b6d3d4c6f5bd9217cf10543f9c11fe42894724e304671ae0ce37ed54b69a29622ebb0e50000000000000000d8c621c4723ba15474ccf0dfc988bad1019a284f499a68da321146595c8b6b2375fa0cfa8c3143f5603a3b2231b758c5b829d081f643b1d0a1b96b79dc97e08353aba844f2665e627cdb364ded642e0a67da60c060976995e358bf4e877478a83e39ac7cbbac543480a419de41bb41aa98bcf61719c9c993fbb2fe4746ad192d16b50f74090b63f213f95531db5b63068fd807fe4d87019bf54dadb030ae488dcdd647d9cc8dc7888eea8d8fc6a95fe2";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_RealProof_HASH_MetaTamper_Fails() public {
        bytes memory proof = hex"bc3ede294b6d3d4c6f5bd9217cf10543f9c11fe42894724e304671ae0ce37ed54b69a29622ebb0e50000000000000000d8c621c4723ba15474ccf0dfc988bad1019a284f499a68da321146595c8b6b2375fa0cfa8c3143f5603a3b2231b758c5b829d081f643b1d0a1b96b79dc97e08353aba844f2665e627cdb364ded642e0a67da60c060976995e358bf4e877478a83e39ac7cbbac543480a419de41bb41aa98bcf61719c9c993fbb2fe4746ad192d16b50f74090b63f213f95531db5b63068fd807fe4d87019bf54dadb030ae488dcdd647d9cc8dc7888eea8d8fc6a95fe2";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }
}
