// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by scripts/tools/generate_glyph_verifier_constants.py. Do not edit by hand.
abstract contract GLYPHVerifierConstants {
    uint256 internal constant MODULUS = 340282366920938463463374607431768211297;
    uint256 internal constant INV140 = 308684718563994177570346965313104020248;
    bytes32 internal constant LIN_DOMAIN = 0x93be526e1b9462164238413e95394f9ec57153d5086f021cea256c173e198550;
}
