// SPDX-License-Identifier: MIT
// AUTO-GENERATED by GLYPH Rust Prover - DO NOT EDIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "./GLYPHVerifier.sol";

contract GLYPH_SNARK_IPA_Test is Test {
    address internal constant TARGET = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;

    function setUp() public {
        vm.chainId(31337);
        GLYPHVerifier impl = new GLYPHVerifier();
        vm.etch(TARGET, address(impl).code);
    }

    function test_GLYPH_SNARK_IPA_Succeeds() public {
        bytes memory proof = hex"799fd1c3013c9115a4d5a18f9c59b15dace290457a7299a2fafdc97ca78fbb5a22f4edba9e0a80a7a4ebde9e3e7a73b118f418a45e4c0a4061f55f76c84f39f8d22e8dcabdff8f198ddc58d048f2ecc71dfeffef6a2a7cd00714b6162c487ba0c096cf84cf49c280b2eb0a3d706aa18905df7007bad6a39727d4a033f9ae05176225966d23f6c80f2f5a566310b1748de65996782711545f0171c7d623a7491fbbbca1a51d57b652b8af51ce9a9696ee2c0ef040e2d61a5cfe20f712cb60814469534e23ae580ce4c7863590e2e38eab32ceb52e95996dd7b188b8ff7e7a29f6";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_IPA_MetaTamper_Fails() public {
        bytes memory proof = hex"799fd1c3013c9115a4d5a18f9c59b15dace290457a7299a2fafdc97ca78fbb5a22f4edba9e0a80a7a4ebde9e3e7a73b118f418a45e4c0a4061f55f76c84f39f8d22e8dcabdff8f198ddc58d048f2ecc71dfeffef6a2a7cd00714b6162c487ba0c096cf84cf49c280b2eb0a3d706aa18905df7007bad6a39727d4a033f9ae05176225966d23f6c80f2f5a566310b1748de65996782711545f0171c7d623a7491fbbbca1a51d57b652b8af51ce9a9696ee2c0ef040e2d61a5cfe20f712cb60814469534e23ae580ce4c7863590e2e38eab32ceb52e95996dd7b188b8ff7e7a29f6";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }
}
