// SPDX-License-Identifier: MIT
// AUTO-GENERATED by GLYPH Rust Prover - DO NOT EDIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "./GLYPHVerifier.sol";

contract GLYPH_SNARK_PLONK_Test is Test {
    address internal constant TARGET = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;

    function setUp() public {
        vm.chainId(31337);
        GLYPHVerifier impl = new GLYPHVerifier();
        vm.etch(TARGET, address(impl).code);
    }

    function test_GLYPH_SNARK_PLONK_Succeeds() public {
        bytes memory proof = hex"c5029d59846bcf4446b78cc6685f4d4b1ffef68c1b91ae6c78107512740aa36d700ac8fdbf309e6a9b5ed6730e7ac6b84ccae45a6193aeb8a7a6d24ba1c7b26b02ce9effb33407b973197f67c6f48fd18cb48d8d5c40346d5f8831ee73520965f0feca506e4553bff70da6e35ad8c217b49cabd06bcabd785e43ed73904026fbb03cc72dda14951009db91afe7ff91444bf75a45b5989817c406827511e3a808cf2fdfecd2b3b16d39a4a1580b5e9fe3c4134aca30c60f395f65a12251a6ed43ddd09f5bb22d820245605c3cf6e1064d9480bb35cbd9a9c20d54fd545149f14a";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_PLONK_MetaTamper_Fails() public {
        bytes memory proof = hex"c5029d59846bcf4446b78cc6685f4d4b1ffef68c1b91ae6c78107512740aa36d700ac8fdbf309e6a9b5ed6730e7ac6b84ccae45a6193aeb8a7a6d24ba1c7b26b02ce9effb33407b973197f67c6f48fd18cb48d8d5c40346d5f8831ee73520965f0feca506e4553bff70da6e35ad8c217b49cabd06bcabd785e43ed73904026fbb03cc72dda14951009db91afe7ff91444bf75a45b5989817c406827511e3a808cf2fdfecd2b3b16d39a4a1580b5e9fe3c4134aca30c60f395f65a12251a6ed43ddd09f5bb22d820245605c3cf6e1064d9480bb35cbd9a9c20d54fd545149f14a";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_SNARK_PLONK_BN254_Succeeds() public {
        bytes memory proof = hex"088b3af110f02ecf1e4436850f315a63c2a61727a5d65aebc2a04cf2105910c77e35785b1ddf3b956449aa908ae62425519172f126b59e04652c9b56959fc8a86efd0e284b886d688d26dcc994a261ac998ca455c17b74d229b32884745b58865dc92a46fe30543b33e26d68e1dc5f3bd6d0c669ed7025edb85c620949044385ea32560faf53b90cd6037892bfd6f393cdbf4c4b1235ab2d0cc24272d354083e412d2d85a2599b40a059d773af65d691537e84d9ae1886df316fadd43039362695f01f4cce7ffbd2a89eba19b023f8ea9004e00713c4fa26b4bffc3be7dcbcb0";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_PLONK_BN254_MetaTamper_Fails() public {
        bytes memory proof = hex"088b3af110f02ecf1e4436850f315a63c2a61727a5d65aebc2a04cf2105910c77e35785b1ddf3b956449aa908ae62425519172f126b59e04652c9b56959fc8a86efd0e284b886d688d26dcc994a261ac998ca455c17b74d229b32884745b58865dc92a46fe30543b33e26d68e1dc5f3bd6d0c669ed7025edb85c620949044385ea32560faf53b90cd6037892bfd6f393cdbf4c4b1235ab2d0cc24272d354083e412d2d85a2599b40a059d773af65d691537e84d9ae1886df316fadd43039362695f01f4cce7ffbd2a89eba19b023f8ea9004e00713c4fa26b4bffc3be7dcbcb0";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }


    function test_GLYPH_SNARK_HALO2_BN254_Succeeds() public {
        bytes memory proof = hex"7dbd2347b18c24425968473003137855c56b18adc471f52629502461920829c3f4554dc57dac0fd28352d2f341d3f07bfd3b4e256e0126cb3a7c06d94e5cb9c3c26b7894a8ff6de3437c46ae0f90a2c26d4d97d07fc716c70aac4d7126803b108e4b2cb070ac44af40213cbac14f095242cfd82c5eeacb02e1d6d0dadc2f7afb68ee39096f4564b01f042ea8a2ff3341fa06540aaac66a13352a581c2a50d3ae6cfb8f9151c32062d6299fc63e96df34c834633d0b7fda1d0d6127570af0619c765c2238196f90b87ce6fe3ae0081f1b9721a40faf544a5845eec4acb5070cbc";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_HALO2_BN254_MetaTamper_Fails() public {
        bytes memory proof = hex"7dbd2347b18c24425968473003137855c56b18adc471f52629502461920829c3f4554dc57dac0fd28352d2f341d3f07bfd3b4e256e0126cb3a7c06d94e5cb9c3c26b7894a8ff6de3437c46ae0f90a2c26d4d97d07fc716c70aac4d7126803b108e4b2cb070ac44af40213cbac14f095242cfd82c5eeacb02e1d6d0dadc2f7afb68ee39096f4564b01f042ea8a2ff3341fa06540aaac66a13352a581c2a50d3ae6cfb8f9151c32062d6299fc63e96df34c834633d0b7fda1d0d6127570af0619c765c2238196f90b87ce6fe3ae0081f1b9721a40faf544a5845eec4acb5070cbc";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }


    function test_GLYPH_SNARK_HALO2_BLS12381_Succeeds() public {
        bytes memory proof = hex"f285d89732e2e350032511fed1d432e98185ca5142ec414fe98fb288acc3b48c7d16fb5c207757cb9de8eed7a877820f52f9942c5d21b22028bf4c734278945a6cd68c10fd74560a4b7f5fd6d5476b1ad9001f2b02958bcc28d9900caff71fe92b795d57598481e0cc13c11c7595667521b9a3d71a6787a359c4e080095583c63625e6d022ff2df6746692aaa9f40239bbe4d69bef7db97e28268ae5d0c3170d00654961377320d6e79592070f5baa899c37d51dc40e5afe6df755dc3b9a7bf67ac9b8191ac8ee24e1edfd6310134969336a6606946423057f8acdb45dfd148d";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_HALO2_BLS12381_MetaTamper_Fails() public {
        bytes memory proof = hex"f285d89732e2e350032511fed1d432e98185ca5142ec414fe98fb288acc3b48c7d16fb5c207757cb9de8eed7a877820f52f9942c5d21b22028bf4c734278945a6cd68c10fd74560a4b7f5fd6d5476b1ad9001f2b02958bcc28d9900caff71fe92b795d57598481e0cc13c11c7595667521b9a3d71a6787a359c4e080095583c63625e6d022ff2df6746692aaa9f40239bbe4d69bef7db97e28268ae5d0c3170d00654961377320d6e79592070f5baa899c37d51dc40e5afe6df755dc3b9a7bf67ac9b8191ac8ee24e1edfd6310134969336a6606946423057f8acdb45dfd148d";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

}
