// SPDX-License-Identifier: MIT
// AUTO-GENERATED by GLYPH Rust Prover - DO NOT EDIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "./GLYPHVerifier.sol";

contract GLYPH_SNARK_KZG_Test is Test {
    address internal constant TARGET = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;

    function setUp() public {
        vm.chainId(31337);
        GLYPHVerifier impl = new GLYPHVerifier();
        vm.etch(TARGET, address(impl).code);
    }

    function test_GLYPH_SNARK_KZG_Succeeds() public {
        bytes memory proof = hex"22f6cf8d3f3e5c21cc7b43a20187b351c78a2beee662204d0832521fc9ba6a3c6c0446973cef83b800000000000000005b58ad8caad1e5477ec8c095635fe3e46e93f2982414e6b165d2b6523d908688e8ac868aa958099fd6f29c4713b43c2bd08e564cca9f3a5fbcf0d31806939d2628265b52e36d6a533f4dc90cd7d087a4cadd799a9ff8114c18aa33e078b3565bf04a33c620daa15abdcf2853828d090bb9803fd4c3d635ae559b1a43335baa4e6c2d92ff7ef3b4b5133d29d5d6a97368ce9d67b17235996836db1d421646be90fd6f8f8edae646f58574ab359f6b4ec0";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_KZG_MetaTamper_Fails() public {
        bytes memory proof = hex"22f6cf8d3f3e5c21cc7b43a20187b351c78a2beee662204d0832521fc9ba6a3c6c0446973cef83b800000000000000005b58ad8caad1e5477ec8c095635fe3e46e93f2982414e6b165d2b6523d908688e8ac868aa958099fd6f29c4713b43c2bd08e564cca9f3a5fbcf0d31806939d2628265b52e36d6a533f4dc90cd7d087a4cadd799a9ff8114c18aa33e078b3565bf04a33c620daa15abdcf2853828d090bb9803fd4c3d635ae559b1a43335baa4e6c2d92ff7ef3b4b5133d29d5d6a97368ce9d67b17235996836db1d421646be90fd6f8f8edae646f58574ab359f6b4ec0";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }


    function test_GLYPH_SNARK_KZG_BLS12381_Succeeds() public {
        bytes memory proof = hex"ef76a145aa3c0b2c9db3f39c73b0399402ad0e13986094ca9d184326cb8d5be8ffaae2b02560c3aa247e9c41bead181f845c03b4b2bff0a7310836614a0e3f2e3ead1424b15538124642efcdc374af4f303e8cc3ffdc5cb15afebf4732e0acdb64b317f68dce6f820e1f092bdf19ef537eab884135d18f1d591408a5856735a60bc349d6aef184c1a137a66ee5c3c6627650915c484fc81600da045bd718f5103db3258e7b72584087eaa83fa561c4d9b40c4641317f80999ba27448ec94114f4a0b40ad1dbabb64309a60629048b49801ecd7973b0bb0321faa5df6f7205957";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_KZG_BLS12381_MetaTamper_Fails() public {
        bytes memory proof = hex"ef76a145aa3c0b2c9db3f39c73b0399402ad0e13986094ca9d184326cb8d5be8ffaae2b02560c3aa247e9c41bead181f845c03b4b2bff0a7310836614a0e3f2e3ead1424b15538124642efcdc374af4f303e8cc3ffdc5cb15afebf4732e0acdb64b317f68dce6f820e1f092bdf19ef537eab884135d18f1d591408a5856735a60bc349d6aef184c1a137a66ee5c3c6627650915c484fc81600da045bd718f5103db3258e7b72584087eaa83fa561c4d9b40c4641317f80999ba27448ec94114f4a0b40ad1dbabb64309a60629048b49801ecd7973b0bb0321faa5df6f7205957";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

}
