// SPDX-License-Identifier: MIT
// AUTO-GENERATED by GLYPH Rust Prover - DO NOT EDIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "./GLYPHVerifier.sol";

contract GLYPH_SNARK_GROTH16_Test is Test {
    address internal constant TARGET = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;

    function setUp() public {
        vm.chainId(31337);
        GLYPHVerifier impl = new GLYPHVerifier();
        vm.etch(TARGET, address(impl).code);
    }

    function test_GLYPH_SNARK_GROTH16_Succeeds() public {
        bytes memory proof = hex"d4d7d03a81ee985d09c9cb03dc84d70903701b80b81aaf839df3dbd12a804d8b81d0ef2997813d7b0000000000000000c995fbc82fec1b991639d960032e032f0197f2a5617e90e76ec01f5eae11a02fc7ad051aaade42df01ff56a4bba4da67df940e01fb18eb9efa8a5082049ba86f32d33c80781edcb293b32fde51645fa330263e544cc374ba9acf86f66c75d5415b2fb21b7d492c322f34ec61552479a9ab5c1f5f2bc74d73d50e67f41af90e473742935189b470fe5c41859fd792ab566bc8cd4823e3fb53c4e325c595dff144cfbf63ea584f2acc7340e33597683223";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_GROTH16_MetaTamper_Fails() public {
        bytes memory proof = hex"d4d7d03a81ee985d09c9cb03dc84d70903701b80b81aaf839df3dbd12a804d8b81d0ef2997813d7b0000000000000000c995fbc82fec1b991639d960032e032f0197f2a5617e90e76ec01f5eae11a02fc7ad051aaade42df01ff56a4bba4da67df940e01fb18eb9efa8a5082049ba86f32d33c80781edcb293b32fde51645fa330263e544cc374ba9acf86f66c75d5415b2fb21b7d492c322f34ec61552479a9ab5c1f5f2bc74d73d50e67f41af90e473742935189b470fe5c41859fd792ab566bc8cd4823e3fb53c4e325c595dff144cfbf63ea584f2acc7340e33597683223";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }


    function test_GLYPH_SNARK_GROTH16_BLS12381_Succeeds() public {
        bytes memory proof = hex"b5c048960fe77f85614201cf54a180ed9fa25519ed75876f851211e21d8f86b8f10500930229bc2ee9b315769e6b816aaba8988412443d1d559807d905bbb8463904b92801d3171844fa6c769ea42085622342ce18e00d5dd77c866170e383a67305f3ab610a1122539b4f57225f3be84ea85a2eb7055da238ec1262b74cbec7de860afe2c4b061c353506f14a984da4114a08acb14666347c493d489057d0843378049e9183a84a5e02ce2f4c5d1b43567ea642e9ae607ad17156e98abd333d446476f971ce3d1c02b3798c12b97316d01af3e311e01abd2671bd3ca9e45142";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_SNARK_GROTH16_BLS12381_MetaTamper_Fails() public {
        bytes memory proof = hex"b5c048960fe77f85614201cf54a180ed9fa25519ed75876f851211e21d8f86b8f10500930229bc2ee9b315769e6b816aaba8988412443d1d559807d905bbb8463904b92801d3171844fa6c769ea42085622342ce18e00d5dd77c866170e383a67305f3ab610a1122539b4f57225f3be84ea85a2eb7055da238ec1262b74cbec7de860afe2c4b061c353506f14a984da4114a08acb14666347c493d489057d0843378049e9183a84a5e02ce2f4c5d1b43567ea642e9ae607ad17156e98abd333d446476f971ce3d1c02b3798c12b97316d01af3e311e01abd2671bd3ca9e45142";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

}
