// SPDX-License-Identifier: MIT
// AUTO-GENERATED by GLYPH Rust Prover - DO NOT EDIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "./GLYPHVerifier.sol";

contract GLYPH_STARK_Test is Test {
    address internal constant TARGET = 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE;

    function setUp() public {
        vm.chainId(31337);
        GLYPHVerifier impl = new GLYPHVerifier();
        vm.etch(TARGET, address(impl).code);
    }

    function test_GLYPH_STARK_F128_Succeeds() public {
        bytes memory proof = hex"4ee3a032fcd58eef0be2db3665cb0c46d296503a9bb36e75e1c216bd37c62522414dff56af0471d177f8c1b49fcd60661799849ef935c136ebdf723df74f90c7fd561978c9fb7da825abef59ab8014dded7e92df3fcc413b2f8ddb42644d7e90fe7261388232af1d25530c23a862917643d3d92ba72f6f9efc64029e359f7d12e74f61d76aae878433bc1f9a60bff0165cd4c8645b474aeb303329115169ec19";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_F128_MetaTamper_Fails() public {
        bytes memory proof = hex"4ee3a032fcd58eef0be2db3665cb0c46d296503a9bb36e75e1c216bd37c62522414dff56af0471d177f8c1b49fcd60661799849ef935c136ebdf723df74f90c7fd561978c9fb7da825abef59ab8014dded7e92df3fcc413b2f8ddb42644d7e90fe7261388232af1d25530c23a862917643d3d92ba72f6f9efc64029e359f7d12e74f61d76aae878433bc1f9a60bff0165cd4c8645b474aeb303329115169ec19";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }






    function test_GLYPH_STARK_Plonky3_BabyBear_Poseidon2_Succeeds() public {
        bytes memory proof = hex"59830b4f8446402454b0deb457d22b4bb6facb94864aff1c17bdc0ba5b1e3fd1ecd3570e30fe58590ef3180ff960da560416ce428a634cb9fb888c511b42615771131dc850e213fd680c2403b50254a18bc85f4e89f370bcb9f9b49ff93739e6bb13261f5119089e016b6aade35f6b873eb9cd5c4c5ce8cfbe734d00ca5b7db5bf0bf4d60bc8e7789642a33fc1badf5d279bc54deaf8ae07467733addca711a0";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Poseidon2_MetaTamper_Fails() public {
        bytes memory proof = hex"59830b4f8446402454b0deb457d22b4bb6facb94864aff1c17bdc0ba5b1e3fd1ecd3570e30fe58590ef3180ff960da560416ce428a634cb9fb888c511b42615771131dc850e213fd680c2403b50254a18bc85f4e89f370bcb9f9b49ff93739e6bb13261f5119089e016b6aade35f6b873eb9cd5c4c5ce8cfbe734d00ca5b7db5bf0bf4d60bc8e7789642a33fc1badf5d279bc54deaf8ae07467733addca711a0";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Poseidon2_Tribonacci_Succeeds() public {
        bytes memory proof = hex"152311d5761539991f6e2e8cc92eebccb6a622f3548cdcdb42d6ae6edc67feaaa83bd648b4d3a326ab132dcbe64b62faf07357862fb5262870c7b8bee83a34c2e73772f7a7a31c8e83085bd72ddace70799293181af23bbb26cd9132c5e880e32ec1919fef5eb3aec0674d8ccf3aba288f061e577c50b650e86cdd05e32b2992ba2b0798b33b00b701cd56e62f1acf12489757621c8386f1ce4c66bb2bd95c2c";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Poseidon2_Tribonacci_MetaTamper_Fails() public {
        bytes memory proof = hex"152311d5761539991f6e2e8cc92eebccb6a622f3548cdcdb42d6ae6edc67feaaa83bd648b4d3a326ab132dcbe64b62faf07357862fb5262870c7b8bee83a34c2e73772f7a7a31c8e83085bd72ddace70799293181af23bbb26cd9132c5e880e32ec1919fef5eb3aec0674d8ccf3aba288f061e577c50b650e86cdd05e32b2992ba2b0798b33b00b701cd56e62f1acf12489757621c8386f1ce4c66bb2bd95c2c";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Poseidon_Succeeds() public {
        bytes memory proof = hex"5a28254e6ac8623adf547e545b8f454ff3c192806fa27c85e09189d29b8f73a064189136ed2230ddbeb9bb85b01fe7b01b6ecdd9873a9f393f82634f8b7ff19044aad630544480a93bb29df2ce55c6bde0eded05a641c91fe561f3d7cb418079f4a5d256b67a24837064db0efc63309f089693f544d44d690108ddec20e6d1522f28ef3018d124bb8502bbac7aa25bb6b2abe196fc409a859d14be043db31374";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Poseidon_MetaTamper_Fails() public {
        bytes memory proof = hex"5a28254e6ac8623adf547e545b8f454ff3c192806fa27c85e09189d29b8f73a064189136ed2230ddbeb9bb85b01fe7b01b6ecdd9873a9f393f82634f8b7ff19044aad630544480a93bb29df2ce55c6bde0eded05a641c91fe561f3d7cb418079f4a5d256b67a24837064db0efc63309f089693f544d44d690108ddec20e6d1522f28ef3018d124bb8502bbac7aa25bb6b2abe196fc409a859d14be043db31374";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Rescue_Succeeds() public {
        bytes memory proof = hex"ba4a46549dcc44157302d6539f728a1c22834193f3b64a49943b297f401173ba740def472911b0abf44fc7aa3d67d52f08bde4a04f2d0ea3c3059bddf1cefce1e29b4c800123e4c9318f87235c871904ca350390926961daff7d3ebbab3dea636b4c0a0e769dd37da6d2437ac9095e5025f324df11eb8a5f1b61fc7d74e3000136656aebeaeb5ac8eff949460d89271d216f53b142a9e155caa0144a34422f38";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Rescue_MetaTamper_Fails() public {
        bytes memory proof = hex"ba4a46549dcc44157302d6539f728a1c22834193f3b64a49943b297f401173ba740def472911b0abf44fc7aa3d67d52f08bde4a04f2d0ea3c3059bddf1cefce1e29b4c800123e4c9318f87235c871904ca350390926961daff7d3ebbab3dea636b4c0a0e769dd37da6d2437ac9095e5025f324df11eb8a5f1b61fc7d74e3000136656aebeaeb5ac8eff949460d89271d216f53b142a9e155caa0144a34422f38";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Blake3_Succeeds() public {
        bytes memory proof = hex"b8e8c9a5a07232e94379ec5e19a8557e7487ed18167cf8f3184dcb11179a7f6df840e807c7a10e0eb0edfa8246c6327fa0fc49974dd4ac7894b0de0f314705afc63293b973d08374630dadffc6bde9bd3affc3885dd5be7ddec50d6fe28c704e51b85000a9d80135ede30cf3d5d421caadc00a3289955883e6e2e78b00637eb0b1c7cc02e093cb8544551902d6de8394e792a5712697761e51ab76404aa82ff5";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_BabyBear_Blake3_MetaTamper_Fails() public {
        bytes memory proof = hex"b8e8c9a5a07232e94379ec5e19a8557e7487ed18167cf8f3184dcb11179a7f6df840e807c7a10e0eb0edfa8246c6327fa0fc49974dd4ac7894b0de0f314705afc63293b973d08374630dadffc6bde9bd3affc3885dd5be7ddec50d6fe28c704e51b85000a9d80135ede30cf3d5d421caadc00a3289955883e6e2e78b00637eb0b1c7cc02e093cb8544551902d6de8394e792a5712697761e51ab76404aa82ff5";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Poseidon2_Succeeds() public {
        bytes memory proof = hex"621a135bff969f9e8bf8e9a3b1229efdf596c7a685a971b9318b379ab14d24dd0c8ef627777a86cd409bf98d05194f2eb4b115d378725c70c9412f6e1fc50ae1e0fa0c45e43191370a51b308948aa173e9307a454d837bdff248d479fa64b6421f3560dc195f2981a21a4a917ef42dde968a56b7b5f15cdcf140831d25e944334e02a369b10de80117e00465bd4a86b9956aa5fa73ba8c4643d8461879c17d47";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Poseidon2_MetaTamper_Fails() public {
        bytes memory proof = hex"621a135bff969f9e8bf8e9a3b1229efdf596c7a685a971b9318b379ab14d24dd0c8ef627777a86cd409bf98d05194f2eb4b115d378725c70c9412f6e1fc50ae1e0fa0c45e43191370a51b308948aa173e9307a454d837bdff248d479fa64b6421f3560dc195f2981a21a4a917ef42dde968a56b7b5f15cdcf140831d25e944334e02a369b10de80117e00465bd4a86b9956aa5fa73ba8c4643d8461879c17d47";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Poseidon2_Tribonacci_Succeeds() public {
        bytes memory proof = hex"bd49317e8e1190b8d7c6fbacdffa9dad86f959ca528348e8ca48a4a801074e06d46243be84058fa5c86ef3d5e3f8afff0f2bc8958e9ff55f802c70eb4fe7b2aabc64fc746f017d95fc63bc0265418c4b82f22cfc655e0fc80057636b8a728ed92e68834936aa4909457a4ebe3f322f713192afbc2541cfd26d09a8167d3095c8af6819f6d218f930c557c4be75399af975a0b54158271001fb58c4812b316b0b";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Poseidon2_Tribonacci_MetaTamper_Fails() public {
        bytes memory proof = hex"bd49317e8e1190b8d7c6fbacdffa9dad86f959ca528348e8ca48a4a801074e06d46243be84058fa5c86ef3d5e3f8afff0f2bc8958e9ff55f802c70eb4fe7b2aabc64fc746f017d95fc63bc0265418c4b82f22cfc655e0fc80057636b8a728ed92e68834936aa4909457a4ebe3f322f713192afbc2541cfd26d09a8167d3095c8af6819f6d218f930c557c4be75399af975a0b54158271001fb58c4812b316b0b";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Poseidon_Succeeds() public {
        bytes memory proof = hex"65d8eb391c8de86f76444aee630a40fb619ffcbefc951a317723f42d4921ba485f11bba8b4d58ea77068ebeb9cb890ff8426bd8a31bada83e61520682b57b2c1b7512549675f7fc99f939007f1eb4d491aec55518a77b4ca701631e51525bc392dbc5d2df8d88312d81b60c3897a5e708d6117c53c940168d02e0928a3f76034664bbd4b6772113e82ab0c801a2cdf411575261ee599bf5e28b8ce6b01a5ba25";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Poseidon_MetaTamper_Fails() public {
        bytes memory proof = hex"65d8eb391c8de86f76444aee630a40fb619ffcbefc951a317723f42d4921ba485f11bba8b4d58ea77068ebeb9cb890ff8426bd8a31bada83e61520682b57b2c1b7512549675f7fc99f939007f1eb4d491aec55518a77b4ca701631e51525bc392dbc5d2df8d88312d81b60c3897a5e708d6117c53c940168d02e0928a3f76034664bbd4b6772113e82ab0c801a2cdf411575261ee599bf5e28b8ce6b01a5ba25";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Rescue_Succeeds() public {
        bytes memory proof = hex"f058aa873ea2a86aa444740720d6eaf2afd1c026f1966c411d5a0f79cad7c99801b57506b69d7c5a240da75f72b44b0f862c986ce0782a85be530accb80a83dcbf080577c5ee82929d958bc89750f89180765aab6c709de52a4c6dfa74f91ad0ded4fbeb68fb1e176989ccee4c54d05a39c9604fcedf0ceabb456534bd4122bf388a78afaca81a59c983d296e4ead2d51b8e8e3912672e1c7f0bcf8eab6373a1";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Rescue_MetaTamper_Fails() public {
        bytes memory proof = hex"f058aa873ea2a86aa444740720d6eaf2afd1c026f1966c411d5a0f79cad7c99801b57506b69d7c5a240da75f72b44b0f862c986ce0782a85be530accb80a83dcbf080577c5ee82929d958bc89750f89180765aab6c709de52a4c6dfa74f91ad0ded4fbeb68fb1e176989ccee4c54d05a39c9604fcedf0ceabb456534bd4122bf388a78afaca81a59c983d296e4ead2d51b8e8e3912672e1c7f0bcf8eab6373a1";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Blake3_Succeeds() public {
        bytes memory proof = hex"5988156b0a7dafc3ce56986a29d8ad12a44be50b2a88e3318e6937a9318268ac8e33f24878ca11b1447120e4b2f29d38f0f1ea2ead26dff2573e566d6a38ede2cc6975e69710b27b2120f24a8272679ddbcffd78b044a8a7672f2e1b38802278aa1c53dbffae4aa84da531965dd7e2c17a07552beca23d0635a89f92c2028a7b158a6bd8802dd260408d8a953826a8c34580bdf990c539d90125e891a02e2842";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_KoalaBear_Blake3_MetaTamper_Fails() public {
        bytes memory proof = hex"5988156b0a7dafc3ce56986a29d8ad12a44be50b2a88e3318e6937a9318268ac8e33f24878ca11b1447120e4b2f29d38f0f1ea2ead26dff2573e566d6a38ede2cc6975e69710b27b2120f24a8272679ddbcffd78b044a8a7672f2e1b38802278aa1c53dbffae4aa84da531965dd7e2c17a07552beca23d0635a89f92c2028a7b158a6bd8802dd260408d8a953826a8c34580bdf990c539d90125e891a02e2842";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Poseidon2_Succeeds() public {
        bytes memory proof = hex"8680faff9cb2fe146af5a22a4a662d6d33fa319a60e7f4d8f45f45a8dbc335cb709d86745bd1647a62e1c5da58a49280dbd3eb016ab7276bcbdbb4297e2a4940830feec1da2367e75997492556a7b59cb73e6559e0ae0784b9bee90ce5f8569f9f10aa16dfa1e160430e29d612d95b6bb2e565551069775de86e9cac71719a8abc3de62e722e752f3b0c3d756b54876241d8c297be346d92d0a6ba467de5bc39";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Poseidon2_MetaTamper_Fails() public {
        bytes memory proof = hex"8680faff9cb2fe146af5a22a4a662d6d33fa319a60e7f4d8f45f45a8dbc335cb709d86745bd1647a62e1c5da58a49280dbd3eb016ab7276bcbdbb4297e2a4940830feec1da2367e75997492556a7b59cb73e6559e0ae0784b9bee90ce5f8569f9f10aa16dfa1e160430e29d612d95b6bb2e565551069775de86e9cac71719a8abc3de62e722e752f3b0c3d756b54876241d8c297be346d92d0a6ba467de5bc39";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Poseidon2_Tribonacci_Succeeds() public {
        bytes memory proof = hex"a8e41235ceb859ee429df75a5214c00c015b2c251593dffdd5abd82ce475a532d1cec3984d699dc242312d45347b1ac8392bce5878ffd3d5c29d07839a057baa3cc057d6e8217b8a5fbff060f3176cfa67e3b231ddb2b020a6f06f60a76f5402df9e4c8deb863f2040e6a03c711d9303a856942b7b29e18744b32c9e6d894c55c254f8609bc34981571e0a5775567acdce1e216feaad298a248ccaf087a4110e";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Poseidon2_Tribonacci_MetaTamper_Fails() public {
        bytes memory proof = hex"a8e41235ceb859ee429df75a5214c00c015b2c251593dffdd5abd82ce475a532d1cec3984d699dc242312d45347b1ac8392bce5878ffd3d5c29d07839a057baa3cc057d6e8217b8a5fbff060f3176cfa67e3b231ddb2b020a6f06f60a76f5402df9e4c8deb863f2040e6a03c711d9303a856942b7b29e18744b32c9e6d894c55c254f8609bc34981571e0a5775567acdce1e216feaad298a248ccaf087a4110e";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Poseidon_Succeeds() public {
        bytes memory proof = hex"79725dc49def6cf544e4312d7effe195e82a19a4cc6ad00fc1cc4ac82a18c209c375bc56759080e46587199a30aa5ae30a8079f42f3c124dbbfc3c501be77748c536008a880f85acc3403c2990238be83a4424e8b6f1a3f8a1fae72829a50d9427e728438729c6607719efcf98af938a2e3fbb44615137bbbee67ed7b7e4a130dc942bfbfa94ce4dfff6c937a33a000ade89b128787cbf8c9169b7d4259970cc";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Poseidon_MetaTamper_Fails() public {
        bytes memory proof = hex"79725dc49def6cf544e4312d7effe195e82a19a4cc6ad00fc1cc4ac82a18c209c375bc56759080e46587199a30aa5ae30a8079f42f3c124dbbfc3c501be77748c536008a880f85acc3403c2990238be83a4424e8b6f1a3f8a1fae72829a50d9427e728438729c6607719efcf98af938a2e3fbb44615137bbbee67ed7b7e4a130dc942bfbfa94ce4dfff6c937a33a000ade89b128787cbf8c9169b7d4259970cc";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Rescue_Succeeds() public {
        bytes memory proof = hex"4d49b05b3b235147aab166173d0eca07ef2c2c770822cf34c7ae86f1fdb54dd699be4727a56931030a83ac5a70ca257019fba2edd575ee8efa1e1bc11f025e1ea93fee5dcfeb2ca7e6f43ba9126aaae83a1391b7e068e9d2319fd458c7ae8c4b91f55949c8a0e93c91cda724b461dc9a1655429642acaa066d628b9f40fd6e8cda1f08f6d62dce356083f151b6b1cfc78510976bdafbc6cebf238fc738bda54e";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Rescue_MetaTamper_Fails() public {
        bytes memory proof = hex"4d49b05b3b235147aab166173d0eca07ef2c2c770822cf34c7ae86f1fdb54dd699be4727a56931030a83ac5a70ca257019fba2edd575ee8efa1e1bc11f025e1ea93fee5dcfeb2ca7e6f43ba9126aaae83a1391b7e068e9d2319fd458c7ae8c4b91f55949c8a0e93c91cda724b461dc9a1655429642acaa066d628b9f40fd6e8cda1f08f6d62dce356083f151b6b1cfc78510976bdafbc6cebf238fc738bda54e";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Blake3_Succeeds() public {
        bytes memory proof = hex"485959f1048e63f7ad4ac928c2c8e956d3a9c635d20fbebe5bbe9cf8bc2ff04ba2bedc3cce4dd61de9d5dd5bcb628494f435e177307018b0bd6d3ea95341e9433b704893232dbdec117654aabc55fc0c22587b46576b2e90f7ee6e6ae76bd8cd51b4aef71f6a9cdc8e36b1d94673d9103af50938805083b9f87498a8ea41a7b72bb4987c86d0e43d71cb1fbadc3611e8246d357bce74ea7f317e1527574b98bc";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Plonky3_Goldilocks_Blake3_MetaTamper_Fails() public {
        bytes memory proof = hex"485959f1048e63f7ad4ac928c2c8e956d3a9c635d20fbebe5bbe9cf8bc2ff04ba2bedc3cce4dd61de9d5dd5bcb628494f435e177307018b0bd6d3ea95341e9433b704893232dbdec117654aabc55fc0c22587b46576b2e90f7ee6e6ae76bd8cd51b4aef71f6a9cdc8e36b1d94673d9103af50938805083b9f87498a8ea41a7b72bb4987c86d0e43d71cb1fbadc3611e8246d357bce74ea7f317e1527574b98bc";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_Miden_Rpo_Succeeds() public {
        bytes memory proof = hex"3b4d95c8ee573f958352b9b5f25b903ccbf74048c17003a52bd745c19fc058cf8bc67fdb5d7215a042a89ea765dcf0de81a0a2a126280dc24ccce2fddfdf99c2d44d2b7ae850910574224993a62042e160c7854fc7199e4cde9a76a166671f5ee93fffd9768cda8a3f3c67d38db2814e8b7cf820e65d5d4c9c50080c78a763b4c30da779b5977dafb711bbb7548e9a05d0064e5b3988ac452440535cafa1aa6a";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Miden_Rpo_MetaTamper_Fails() public {
        bytes memory proof = hex"3b4d95c8ee573f958352b9b5f25b903ccbf74048c17003a52bd745c19fc058cf8bc67fdb5d7215a042a89ea765dcf0de81a0a2a126280dc24ccce2fddfdf99c2d44d2b7ae850910574224993a62042e160c7854fc7199e4cde9a76a166671f5ee93fffd9768cda8a3f3c67d38db2814e8b7cf820e65d5d4c9c50080c78a763b4c30da779b5977dafb711bbb7548e9a05d0064e5b3988ac452440535cafa1aa6a";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }

    function test_GLYPH_STARK_Miden_Blake3_Succeeds() public {
        bytes memory proof = hex"9c10bc909b292f56e50ebeaeec77216abe5651ce4e58698a14e4335cc71522ce737e841e46810300273c4447b45be296795e7b12f53c59670b93a425c85cf1c63155f0e51cfa19e9732de8f90edfec1c6468f0c40cb0deb35766a6136841f1220902e0ef7b3760e71d53b5a9dc32de26f83894f021a6492b4aa8e43d5ca396e3215f1fb3e0dc0887ab8054ce4e6eff0a715e6e71718ef29bf654583b68457dc1";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Miden_Blake3_MetaTamper_Fails() public {
        bytes memory proof = hex"9c10bc909b292f56e50ebeaeec77216abe5651ce4e58698a14e4335cc71522ce737e841e46810300273c4447b45be296795e7b12f53c59670b93a425c85cf1c63155f0e51cfa19e9732de8f90edfec1c6468f0c40cb0deb35766a6136841f1220902e0ef7b3760e71d53b5a9dc32de26f83894f021a6492b4aa8e43d5ca396e3215f1fb3e0dc0887ab8054ce4e6eff0a715e6e71718ef29bf654583b68457dc1";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_Cairo_Stone6_Keccak160_Succeeds() public {
        bytes memory proof = hex"1beee1fa9e01a201ee516d7ed73a5c51b88a3274ccc1d09d81b605a27f4854996bf61d18247e5ebf0ad282d14b55b4fa44a2a256e77f0a927886155f6f665c67b8f3e9b87305caf2711f1d46c29f175c1cd595389436319e4b71c500b9fc9378bc0e9dc2bb64695a44bec1137e3bab93b6b9af9035c58320953b9e9b7f98bc44f817796130435963366bd38de672435352a526005631662a60a81dbee9b52f55";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Cairo_Stone6_Keccak160_MetaTamper_Fails() public {
        bytes memory proof = hex"1beee1fa9e01a201ee516d7ed73a5c51b88a3274ccc1d09d81b605a27f4854996bf61d18247e5ebf0ad282d14b55b4fa44a2a256e77f0a927886155f6f665c67b8f3e9b87305caf2711f1d46c29f175c1cd595389436319e4b71c500b9fc9378bc0e9dc2bb64695a44bec1137e3bab93b6b9af9035c58320953b9e9b7f98bc44f817796130435963366bd38de672435352a526005631662a60a81dbee9b52f55";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }


    function test_GLYPH_STARK_Circle_Succeeds() public {
        bytes memory proof = hex"515ab10d0e9894659445a749bde647f96fbcd238803e7bd0a61d02ffba4d2303d3be0bcfe85e2ea3dadd12c28d91cfbb505b3beffa6db7367b33b5dda8bc8077a9be60fc98605b484bdd1e3173630e6f96e6c3477ecf862c4070bd4daefaf8425308caac83c279ec629df66d44542a2b68e2bb88b97d3bb3747afb7d30e384292cbd83e85af87cddeb5c2b2a1d70fe307eeb33849728fb8d960545241ef3fd16";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Circle_MetaTamper_Fails() public {
        bytes memory proof = hex"515ab10d0e9894659445a749bde647f96fbcd238803e7bd0a61d02ffba4d2303d3be0bcfe85e2ea3dadd12c28d91cfbb505b3beffa6db7367b33b5dda8bc8077a9be60fc98605b484bdd1e3173630e6f96e6c3477ecf862c4070bd4daefaf8425308caac83c279ec629df66d44542a2b68e2bb88b97d3bb3747afb7d30e384292cbd83e85af87cddeb5c2b2a1d70fe307eeb33849728fb8d960545241ef3fd16";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }


    function test_GLYPH_STARK_Circle_Poseidon_M31_Succeeds() public {
        bytes memory proof = hex"2ce9cadf4372968e0d683519b310178bd42320baca69b1e48c31d2e2ba078755421f36cb7c10bbf3d84d96e8ec87ee7fffc2c5ef78c13fa13d8969c4488ec05425eb137d8f0fc14bb2a4410a1610bfe101b47435b5cc4fe5eb6aa03405200ac33d9754bf3be07ddbf67b13e4599ed35346647dde01dbcb41bad62a9fe47a72ca52655afd8db7904848c26b9a080157ca73dfe16bd8d940936d76c26b525186b3";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Circle_Poseidon_M31_MetaTamper_Fails() public {
        bytes memory proof = hex"2ce9cadf4372968e0d683519b310178bd42320baca69b1e48c31d2e2ba078755421f36cb7c10bbf3d84d96e8ec87ee7fffc2c5ef78c13fa13d8969c4488ec05425eb137d8f0fc14bb2a4410a1610bfe101b47435b5cc4fe5eb6aa03405200ac33d9754bf3be07ddbf67b13e4599ed35346647dde01dbcb41bad62a9fe47a72ca52655afd8db7904848c26b9a080157ca73dfe16bd8d940936d76c26b525186b3";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_Circle_Rescue_M31_Succeeds() public {
        bytes memory proof = hex"a348925cb461f797e6f0008671ca7b2ec1ba683d15f534a7b4c42b38efd8c2343bfc9101bfabdd280dea6d825296942179da0ef968a1dbf884884cdca8a11e90e5712fffcfbc43a8a534378bc20d5656f9449f1e869e49a721563f0bb5819184223282b55175bf55630f82b3509834ccdea3e81e7ab4cb2015adee830e24b08c3c8b83e390d0a76a65a9233f2335362e929dc62b0e456a937d1699c4dbab929f";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Circle_Rescue_M31_MetaTamper_Fails() public {
        bytes memory proof = hex"a348925cb461f797e6f0008671ca7b2ec1ba683d15f534a7b4c42b38efd8c2343bfc9101bfabdd280dea6d825296942179da0ef968a1dbf884884cdca8a11e90e5712fffcfbc43a8a534378bc20d5656f9449f1e869e49a721563f0bb5819184223282b55175bf55630f82b3509834ccdea3e81e7ab4cb2015adee830e24b08c3c8b83e390d0a76a65a9233f2335362e929dc62b0e456a937d1699c4dbab929f";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_BabyBear_Succeeds() public {
        bytes memory proof = hex"757dceb83ef2dfcd8566b7bbfd55be48f2c95b3b711bfc315655fafaac4a85aa74c3f5a6410f0f9aa8071c31c08a0e9eba39efa06c3ca6f3401d469340f3333330cd45901715186c0dff928c4e385cbdb9bf5bea4cb15d64874405390f92c68bdc5c23a7bb4244107cfc6c617fa7416b0211d39643ec52d5d1ff046f7bfc2d4d1d75d3e5c9b81db694991774a398078e5ec424bce9aeffda0f5808a906c4d63a";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_BabyBear_MetaTamper_Fails() public {
        bytes memory proof = hex"757dceb83ef2dfcd8566b7bbfd55be48f2c95b3b711bfc315655fafaac4a85aa74c3f5a6410f0f9aa8071c31c08a0e9eba39efa06c3ca6f3401d469340f3333330cd45901715186c0dff928c4e385cbdb9bf5bea4cb15d64874405390f92c68bdc5c23a7bb4244107cfc6c617fa7416b0211d39643ec52d5d1ff046f7bfc2d4d1d75d3e5c9b81db694991774a398078e5ec424bce9aeffda0f5808a906c4d63a";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_Circle_Poseidon_BabyBear_Succeeds() public {
        bytes memory proof = hex"d7776003bbaba8df22525b3a19ab69ee1b83fe1b062f6ebd4e163c84da69c0e96309d420c353dfe78fb1ff7ff729b2c4b11bac4cb3365617c1ef8b4b46b993c042b65b19715810a48c767c6c5aa8bba1eb0e56fa9fa2d9bc03d3d10bf58b7e7348df9d28b8c775518b449d1f6610dd7f65f56df3d8afa55793d21b2f2bf78a224304e7e287b0ab676a2245d5d758f3723ed165c4ed9cf82d94bae585399b4cf7";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Circle_Poseidon_BabyBear_MetaTamper_Fails() public {
        bytes memory proof = hex"d7776003bbaba8df22525b3a19ab69ee1b83fe1b062f6ebd4e163c84da69c0e96309d420c353dfe78fb1ff7ff729b2c4b11bac4cb3365617c1ef8b4b46b993c042b65b19715810a48c767c6c5aa8bba1eb0e56fa9fa2d9bc03d3d10bf58b7e7348df9d28b8c775518b449d1f6610dd7f65f56df3d8afa55793d21b2f2bf78a224304e7e287b0ab676a2245d5d758f3723ed165c4ed9cf82d94bae585399b4cf7";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_Circle_Rescue_BabyBear_Succeeds() public {
        bytes memory proof = hex"e9380c41dbdf323f7249dce2557787f9bcd3cd50d604517f9db08b2d21dd1758a4eaead4fdaa87448bfb19dedb04b0e606c58645d2532d870167d3e4049d546c026cf2d5c532260b4ddcec7c5dc34c97efe4e14d8d9fd48cf73a35906d2e661839f0a585bf9d0721f1e67ca9aa73a4424c7ae1d7479bd3f8e953d6847aa6d6f7bae5e7375d2329576e0543e25da810d9935c994fb66c7783724ad838009620d5";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Circle_Rescue_BabyBear_MetaTamper_Fails() public {
        bytes memory proof = hex"e9380c41dbdf323f7249dce2557787f9bcd3cd50d604517f9db08b2d21dd1758a4eaead4fdaa87448bfb19dedb04b0e606c58645d2532d870167d3e4049d546c026cf2d5c532260b4ddcec7c5dc34c97efe4e14d8d9fd48cf73a35906d2e661839f0a585bf9d0721f1e67ca9aa73a4424c7ae1d7479bd3f8e953d6847aa6d6f7bae5e7375d2329576e0543e25da810d9935c994fb66c7783724ad838009620d5";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_BabyBearStandard_Succeeds() public {
        bytes memory proof = hex"3b9e22188847fbb5d27b8243f56e588a0467fef8556b1074420574f1cff1f68cda5e995291773f35fae47bfd53cc1adbb83178b4eaee867dd583ea7e12d067eeae66cf353ecbbf3979be6f58274a8976561921f7056aaf3f0ac3f6ea7522abf8e3b7e898c1aa1b0e50f20b8811e9a9b8f32ea45c9f748b93f5283ece1178dbdd88408b10f197553fde1843b8b16a4d417fb0e9cf99ba1e9187edef6cefd1f1b5";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_BabyBearStandard_MetaTamper_Fails() public {
        bytes memory proof = hex"3b9e22188847fbb5d27b8243f56e588a0467fef8556b1074420574f1cff1f68cda5e995291773f35fae47bfd53cc1adbb83178b4eaee867dd583ea7e12d067eeae66cf353ecbbf3979be6f58274a8976561921f7056aaf3f0ac3f6ea7522abf8e3b7e898c1aa1b0e50f20b8811e9a9b8f32ea45c9f748b93f5283ece1178dbdd88408b10f197553fde1843b8b16a4d417fb0e9cf99ba1e9187edef6cefd1f1b5";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_BabyBearStandard_Blake3_Succeeds() public {
        bytes memory proof = hex"0d2ecdff760fe34a0d72dc3fe1fd9bae157e45f83656d6c6d3df3c538dfe9eff2aef68adfb364558a05ef45a26a42f8cae554ae804cae26acab8aaf98fa23bf837bb0b105989edd4a96b4368679139cb67070cd99f4eea25ae6602cf93002a2845330a3ad94534b96f5d845707b3352f53c91cdd3ad828342a04c371624a0ed4f18210dd0882628d4322b997fbab50f903cfb4aa16220295997bffafa2ab3d3c";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_BabyBearStandard_Blake3_MetaTamper_Fails() public {
        bytes memory proof = hex"0d2ecdff760fe34a0d72dc3fe1fd9bae157e45f83656d6c6d3df3c538dfe9eff2aef68adfb364558a05ef45a26a42f8cae554ae804cae26acab8aaf98fa23bf837bb0b105989edd4a96b4368679139cb67070cd99f4eea25ae6602cf93002a2845330a3ad94534b96f5d845707b3352f53c91cdd3ad828342a04c371624a0ed4f18210dd0882628d4322b997fbab50f903cfb4aa16220295997bffafa2ab3d3c";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_BabyBearStandard_Poseidon_Succeeds() public {
        bytes memory proof = hex"f8e734441ae076a77346fd388fb784cf98825240bd9d321762cb1fefbfbe6787897d3e619489d96d343a53095bf807f80262f5c91fe8c3e80b1c07e90ed5f624821891988c1bbade8258a5c9569ec5588435cd025cc8466c1212225b9c564053c4e567a152826d2b8e057191cbf6229b4fde9798f7954ba053ae75dbbcc11c88325d79c775071771e0b0c6bf46afaab13736e651209a9ead0bb86db29d064e72";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_BabyBearStandard_Poseidon_MetaTamper_Fails() public {
        bytes memory proof = hex"f8e734441ae076a77346fd388fb784cf98825240bd9d321762cb1fefbfbe6787897d3e619489d96d343a53095bf807f80262f5c91fe8c3e80b1c07e90ed5f624821891988c1bbade8258a5c9569ec5588435cd025cc8466c1212225b9c564053c4e567a152826d2b8e057191cbf6229b4fde9798f7954ba053ae75dbbcc11c88325d79c775071771e0b0c6bf46afaab13736e651209a9ead0bb86db29d064e72";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_BabyBearStandard_Rescue_Succeeds() public {
        bytes memory proof = hex"7d6f794cde9fe268fa6f07a6a6421e0917af10585f6a185ac22f06c3583b04d778f6679610d315bf9c6df78f825a1b4efeebc76bb5102e87274da356ec8702b23669b20bf6902bc23cdd42b0d16354bb90d1f7093973532e5c74fb43fe687d5ec10c29886c568a3bac422775df1cf007fd1bdb2a8a2711e20694732481735c8245027b47e81af72ae2271341fda016683efd5b6533e5f0dd267137f8b5c740a0";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_BabyBearStandard_Rescue_MetaTamper_Fails() public {
        bytes memory proof = hex"7d6f794cde9fe268fa6f07a6a6421e0917af10585f6a185ac22f06c3583b04d778f6679610d315bf9c6df78f825a1b4efeebc76bb5102e87274da356ec8702b23669b20bf6902bc23cdd42b0d16354bb90d1f7093973532e5c74fb43fe687d5ec10c29886c568a3bac422775df1cf007fd1bdb2a8a2711e20694732481735c8245027b47e81af72ae2271341fda016683efd5b6533e5f0dd267137f8b5c740a0";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_KoalaBear_Succeeds() public {
        bytes memory proof = hex"8e2c5f03e8a502d93b91650146cb0c62f6defa9423f46e989143425a3fd9617d473c781d37c3f26d405ed63cf43b2839765b98f9fc05d4e0085b32198d96690b80587048697df9bd819b20479a4e14ed391267ef235e1f001fb4f1467f54b63ef0cfd8b8162ec04084e26b6cb2a47c823026c121ef182d0c294716a32966d3b4f7b5c10b2fcdff5b5e3779fa61c2159566822486ac3278d295c1a8e6312b5cc9";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_KoalaBear_MetaTamper_Fails() public {
        bytes memory proof = hex"8e2c5f03e8a502d93b91650146cb0c62f6defa9423f46e989143425a3fd9617d473c781d37c3f26d405ed63cf43b2839765b98f9fc05d4e0085b32198d96690b80587048697df9bd819b20479a4e14ed391267ef235e1f001fb4f1467f54b63ef0cfd8b8162ec04084e26b6cb2a47c823026c121ef182d0c294716a32966d3b4f7b5c10b2fcdff5b5e3779fa61c2159566822486ac3278d295c1a8e6312b5cc9";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_Circle_Poseidon_KoalaBear_Succeeds() public {
        bytes memory proof = hex"f581f3066e1f6709c94e7c8f51e0e1a85a3f47b8cac56cb224a727add4f81c8256454069a0e160511845a56229358fab76bbdfdc8b853d3645c4837e866fc49759455ea96c2e2613f47283f779338ccc4f2663999f3ae3c7114b6753a99d7ef235e6857389a09c1a42fcfd8aeed47b3da2885f62ed5f154a9338574116523e4ed70918b4f27e20b51cb22ee434c15940756acb42d9fa08ba06ad0abd5fad1bd7";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Circle_Poseidon_KoalaBear_MetaTamper_Fails() public {
        bytes memory proof = hex"f581f3066e1f6709c94e7c8f51e0e1a85a3f47b8cac56cb224a727add4f81c8256454069a0e160511845a56229358fab76bbdfdc8b853d3645c4837e866fc49759455ea96c2e2613f47283f779338ccc4f2663999f3ae3c7114b6753a99d7ef235e6857389a09c1a42fcfd8aeed47b3da2885f62ed5f154a9338574116523e4ed70918b4f27e20b51cb22ee434c15940756acb42d9fa08ba06ad0abd5fad1bd7";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



    function test_GLYPH_STARK_Circle_Rescue_KoalaBear_Succeeds() public {
        bytes memory proof = hex"1a986d02bf5a9ca51861ac57c84cb97006e30063487146a2d058339154e61157bbff509f7e2b4c622cc7e0a23e4c992f7dbbe92cf481a866e441821358ea016fcb1e1fc3bf0411a4bddf471fe098ae2df52cca90dde511c2da051db5add05e1b4d4ed1f79dbccefe754deda2bf162bf79676241ffa6ff18972fb53393be4a7451ae67e167dd211a3c931a0fb704c010c173c823598cd168b71d0e3258271f36c";
        (bool ok, bytes memory ret) = TARGET.call(proof);
        assertTrue(ok, "verify should succeed");
        assertEq(abi.decode(ret, (uint256)), 1, "return value");
    }

    function test_GLYPH_STARK_Circle_Rescue_KoalaBear_MetaTamper_Fails() public {
        bytes memory proof = hex"1a986d02bf5a9ca51861ac57c84cb97006e30063487146a2d058339154e61157bbff509f7e2b4c622cc7e0a23e4c992f7dbbe92cf481a866e441821358ea016fcb1e1fc3bf0411a4bddf471fe098ae2df52cca90dde511c2da051db5add05e1b4d4ed1f79dbccefe754deda2bf162bf79676241ffa6ff18972fb53393be4a7451ae67e167dd211a3c931a0fb704c010c173c823598cd168b71d0e3258271f36c";
        proof[31] = bytes1(uint8(proof[31]) ^ 1);
        (bool ok, ) = TARGET.call(proof);
        assertFalse(ok, "meta tamper must revert");
    }



}
